### ISSUE TITLE
Memory Access Violation when attempting to open preferences

### ISSUE THREAD

**Issue by xenia-foxtrot** [SoftFever/OrcaSlicer#10029]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.0

### Operating System (OS)

Linux

### OS Version

Arch Linux, Kernel 6.15.4

### Additional system information

GPU: NVidia GTX 3060, driver version: `nvidia-open-dkms 575.64-1`

### Printer

N/A

### How to reproduce

1. Launch Orca Slicer (I run `orca-slicer`) from the terminal
2. Click on menu
3. Click on "preferences"
4. Program freezes
5. Program terminates with `SIGSEGV (Address boundary error)`

### Actual results

Program terminates with `SIGSEGV (Address boundary error)`

### Expected results

I should be able to see the preferences dialogue. 

### Project file & Debug log uploads

[debug_Sun_Jun_29_16_01_06_2754717.log](https://github.com/user-attachments/files/20970563/debug_Sun_Jun_29_16_01_06_2754717.log)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

This occurs on both the official AppImage version, the git version in the AUR (`orca-slicer-git`).

I understand the AUR version is not officially supported, but since it tracks the development git branch it may be useful for tracking down this issue.

**Comment by MathisP75** [comment]
Same here, I get `segmentation fault (core dumped)  orca-slicer`

**Comment by alex-courtis** [comment]
Confirmed on arch, same version.

Happens under wayland and X11.

Stack trace: [os.10029.backtrace.log](https://github.com/user-attachments/files/21026658/os.10029.backtrace.log)
Might not be getting pango fonts correctly.

~~Bambu studio is ok. The difference might be webkit2gtk version: orca-slicer is `libwebkit2gtk-4.1`, bambu-studio is on `libwebkit2gtk-4.0`~~

~~`ldd /opt/orca-slicer/bin/orca-slicer`
[orca-slicer.ldd.txt](https://github.com/user-attachments/files/21026687/orca-slicer.ldd.txt)~~

~~`/opt/bambustudio-bin/bin/bambu-studio`
[bambu-studio.ldd.txt](https://github.com/user-attachments/files/21026692/bambu-studio.ldd.txt)~~

Edit: `OrcaSlicer-Linux-flatpak_V2.3.0_x86_64.flatpak` is working. The flatpak is using `libwebkit2gtk-4.1.so.0.16.8` with AUR package using `libwebkit2gtk-4.1.so.0.17.8`, hence unlikely to be webkit2gtk version.

**Comment by lodriguez** [comment]
I maintain the AUR-git version. Downgrading Pango to 1:1.56.3-1 works as a workaround. I will take a closer look at this later.

**Comment by lodriguez** [comment]
So I looked into the trace.  It fails when it tries to measure the string `한국어` 
```
else if (vlist[i] == wxLocale::GetLanguageInfo(wxLANGUAGE_KOREAN)) { 
             language_name = wxString::FromUTF8("\xED\x95\x9C\xEA\xB5\xAD\xEC\x96\xB4");        }
```
Pango trys to resolve the font for "NanumGothic" and if it can't, it returns `Null` and orca segfaults

So installing ttf-nanum from the AUR should solve the problem for now. I'm not sure why it just worked with the old pango version.


What is the expected behaviour here? Orca requests a font face - pango can't deliver it and gives an alternative?

**Comment by lodriguez** [comment]
OK I dug a bit further

[btfull.txt](https://github.com/user-attachments/files/21328687/btfull.txt)

These frames from the GDB backtrace should show the critical path to the crash: 0-2, 13, 14 and 20-25

I believe the bug is somewhere in wxWidgets. My guess is, that Pango was a bit more robust before the last update (so there's probably a bug, too. But I couldn't reproduce it with a minimal example). So it could handle the current implementation.  

I haven't looked into building wxWidgets with debug options. But the question here is. Should I even do it? What's the future of wxWidgets, will the fork be re-based anytime soon? Should I look for a workaround in `DropDown::messureSize()` or in the language_name for-loop in `Preferences.cpp`.

installing `NanumGothic` works, but I guess a more robust fix/workaround would be preferable.

**Comment by ipatch** [comment]
thanks for tracking this down @lodriguez 🙏 i was in the process of building orca-slicer from source using homebrew deps, but ran into all sorts of issues trying to build wxwidgets with cmake instead autotools, and then ran into several homebrew related issues with cmake, wxwidgets, and homebrew 😫

> installing NanumGothic works, but I guess a more robust fix/workaround would be preferable.

would it not make sense to make `NanumGothic` a required dep for the orca-slicer aur package that you maintain so other wouldn't run into this issue, and then have to search through the github issue tracker?

**Comment by ipatch** [comment]
i installed the required font package, but orca-slicer is still crashing when i attempt to open the preferences,

```
╰─λ yay -S NanumGothic
 -> No AUR package found for NanumGothic
 there is nothing to do
╭─capin at rogue in /home/capin/homebrew/Library/Taps/homebrew/homebrew-core (ipatch.archlinux.wxwidgets-cmake ✔)
╰─λ yay -Ss NanumGothic
aur/ttf-nanumgothic_coding 2.5-2 (+25 0.00)
    Nanum series fixed width TrueType fonts
```

```
:: Processing package changes...
(1/1) installing ttf-nanumgothic_coding                                        [--------------------------------------------] 100%
```

```
╰─λ coredumpctl list
TIME                            PID  UID GID SIG     COREFILE EXE                       SIZE
Sat 2025-07-05 18:55:02 CDT  141184 1000 984 SIGABRT present  /usr/bin/orca-slicer-bin 91.9M
Wed 2025-07-09 14:40:12 CDT 3142614 1000 984 SIGSEGV present  /usr/bin/orca-slicer-bin 87.9M
Wed 2025-07-09 14:57:03 CDT 3222762 1000 984 SIGABRT present  /usr/bin/superslicer       14M
Wed 2025-07-09 15:00:21 CDT 3243140 1000 984 SIGABRT present  /usr/bin/superslicer     14.1M
Wed 2025-07-16 13:38:43 CDT 3417746 1000 984 SIGSEGV present  /usr/bin/orca-slicer-bin 91.7M
Wed 2025-07-16 14:18:49 CDT 3558680 1000 984 SIGSEGV present  /usr/bin/orca-slicer-bin 84.6M
Wed 2025-07-16 14:39:53 CDT 3602301 1000 984 SIGSEGV present  /usr/bin/orca-slicer-bin 87.9M
Sat 2025-07-19 14:57:55 CDT 1372359 1000 984 SIGSEGV present  /usr/bin/orca-slicer-bin 90.3M
```

**Comment by lodriguez** [comment]
You need to install ttf-nanum from AUR.  ttf-nanumgothic_coding does not include NanumGothic. ttf-nanum has all the nanum fonts.

**Comment by alex-courtis** [comment]
Love your work @lodriguez 

> would it not make sense to make NanumGothic a required dep for the orca-slicer aur package that you maintain so other wouldn't run into this issue, and then have to search through the github issue tracker?

Yes please!
