### ISSUE TITLE
preview completely broken when launching normally on Linux with nvidia GPU

### ISSUE THREAD

**Issue by fiban123** [SoftFever/OrcaSlicer#11723]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1

### Operating System (OS)

Linux

### OS Version

omarchy

### Additional system information

amd cpu
nvidia 4070 super

nvida drivers:
NVIDIA-SMI 580.105.08
CUDA Version: 13.0

newest linux-zen kernel (6.17.9-zen1-1-zen)

### Printer

doesnt matter

### How to reproduce

1. get nvidia gpu
2. install arch linux
3. download the orcaslicer flatpak
4. install the orcaslicer flatpak normally
5. run it
6. no preview for model

### Actual results

<img width="3835" height="2160" alt="Image" src="https://github.com/user-attachments/assets/bf569638-8a6a-443f-b1a3-5b72de0da57c" />

there should be a build plate there

### Expected results

the build plate should appear

### Project file & Debug log uploads

[logs.zip](https://github.com/user-attachments/files/24319216/logs.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

i know this is not an unfixable bug, in fact, i know the fix, but i am still making this issue because you have to set an obscure environment variable in order to get the orcaslicer preview to work.

my fix:
running this in the terminal and then running orcaslicer with flatpak fixes the issue for me:
```
flatpak override --user --env=GBM_BACKEND=dri io.github.softfever.OrcaSlicer
```
(i got this fix issue from a more or less unrelated [issue](https://github.com/OrcaSlicer/OrcaSlicer/issues/9973))

this issue has existed for at least 2 years.
[link to reddit post about this from 2 years ago](https://www.reddit.com/r/OrcaSlicer/comments/16xw6qg/the_linux_missing_preview_issue/)

there have been multiple issues on this, all of which seem to have been more or less ignored, apparent by the fact that it has yet to be fixed.
[issue 1](https://github.com/OrcaSlicer/OrcaSlicer/issues/6666)
[issue 2](https://github.com/OrcaSlicer/OrcaSlicer/issues/8361)

as far as i know, this is related to nvidia drivers and linux.
also on the exact same system, it works fine on windows with the normal installation process.

also, the obscure flag forces orcaslicer to use cpu rendering, evident by the fact that all my 16 cores go crazy when i simply rotate the camera and i also get about 2fps. 

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/ff7eead2-6af0-4f2e-9223-e46c8f150343" />
(all 16 cores are almost fully green in the top right corner)

please someone fix this. this fix is long overdue in my opinion.

**Comment by kernelPanic0x** [comment]
I have the same issue! orca-slicer is unusable with wayland and a nvidia GPU currently. My only fix on arch linux was to switch desktop envoironments to x11 because gnome has removed x11 support in it's newest release 😂

**Comment by kernelPanic0x** [comment]
But it seems that this is not really an issue of orca-slicer, because FreeCAD is broken too. I think its just an openGL ES problem on nvidia's side. They need to get their shit together -.-

**Comment by Scafir** [comment]
This is not restricted to nvidia drivers. I have similar issues where the ui is sometimes working, sometimes broken on Fedora Linux 43 (Workstation Edition), wayland, kernel 6.17.11-300.fc43.x86_64 on GNOME.
I've never had any issues with Freecad (flatpak, v 1.0.2) , despite quite a bit of use.
Even when it seems to run correctly, there are a lot of warnings thrown by GTK, which is likely linked with the issue:

[orca_log_working.txt](https://github.com/user-attachments/files/24346845/orca_log_working.txt)

The UI completely breaking down as in the original post do not seem to create corresponding debug logs.

**Comment by avicarpio** [comment]
Please fix this, it is completely unusable

**Comment by ask6483** [comment]
I ran the orca using following env setting in desktop file:
```
[Desktop Entry]
Type=Application
Name=OrcaSlicer
Comment=Slicer software
Icon=/opt/orcaslicer/icon.png
Exec=env WEBKIT_DISABLE_DMABUF_RENDERER=1 __GLX_VENDOR_LIBRARY_NAME=mesa __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink /opt/orcaslicer/orcaslicer
Terminal=false
Categories=Graphics;Engineering;CAD;
MimeType=model/stl;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;application/x-amf;
StartupWMClass=OrcaSlicer
```
It starts, allows to slice single model but creating multiple build plates or moving the window to the oher monitor/desktop when the model is loaded breaks UI rendering.

**Comment by mosfet80** [comment]
I think it can be solved by using both patches    #11518 #10850

**Comment by Scafir** [comment]
I have a two monitor setup on GNOME and found that  orcaslicer worked better when launched on one monitor than the other. I also had issues with kicad, and found the following thread: https://discussion.fedoraproject.org/t/kicad-and-fedora-43/175578/18
Seems like this fixed with https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4766, which will go in the next release of mutter (the one after 49.2). Maybe this also affects orcaslicer somehow?

I suspect there are multiple overlaying issues breaking the ui. I've installed your patched version, but I need to use it more before I can comment @mosfet80. In any case, thanks for looking into these problems.

**Comment by petersadej** [comment]
I had a very similar issue. Running Bazzite on a RTX 3070.

Updating to a newer Nvidia driver fixed it for me. Specifically 590.48.01-1

**Comment by theogayar** [comment]
Same issue here. I'm on an RTX3080 with the latest rpm available driver, so 580 something... I'm relunctant to switch to 590 using the direct package from Nvidia, but I might if I don't find another solution lol

> Updating to a newer Nvidia driver fixed it for me. Specifically 590.48.01-1

What did you use @petersadej if you don't mind me asking?

**Comment by petersadej** [comment]
> Same issue here. I'm on an RTX3080 with the latest rpm available driver, so 580 something... I'm relunctant to switch to 590 using the direct package from Nvidia, but I might if I don't find another solution lol
> 
> > Updating to a newer Nvidia driver fixed it for me. Specifically 590.48.01-1
> 
> What did you use [@petersadej](https://github.com/petersadej) if you don't mind me asking?

I was able to just update to a newer version of Bazzite because the driver is bundled with Bazzite. Here's the driver repo they use in case it helps: https://github.com/bazzite-org/nvidia-driver

Side note: orcaslicer still doesn't run great for me on the newer driver. It is laggy when doing any 3d operations.

**Comment by petertrotman** [comment]
Confirm working with no additional environment variables with Nvidia 590.48.01-1

Still requires xwayland, however - can't force native rendering.

**Comment by theogayar** [comment]
Thanks for the reply @petersadej, sorry I couldn't get back earlier, it's been a busy few weeks...

I've just tried installing `590.48.01` through akmods by using the release server from Fedora 44, and still no luck for me here. The app starts, and menus respond fine, but the plate view is still broken...

This is really upsetting once again against the green company as my amd-powered laptop has no issues with any app ever lol

**Comment by bigtimer-dev** [comment]
yep also same error here in omarchy.

**Comment by gucio321** [comment]
same issue - Arch. Using aur/orca-slicer-bin (so no flatpak). I'm on the following driver version:
```console
nvidia-580xx-dkms 580.142-2
```
(And can't upgrade to 590 cause I need this specifice driver series for optimus setup)

I believe this is rather the upstream issue (but idk where).
Freecad (weekly) and Prusa Slicer work for me.
