### ISSUE TITLE
Error when slicing with Tree Suppports: Flow::spacing() produced negative spacing. Did you set some extrusion width too small?

### ISSUE THREAD

**Issue by dvomang** [SoftFever/OrcaSlicer#1201]
**Describe the bug**
When I use tree supports with OrcaSlicer I am getting an error that says 
"Flow::spacing() produced negative spacing. Did you set some extrusion width too small?"

**3mf File for This Bug**
3mf attached

**To Reproduce**
Unsure. Try to get Max Volumetric Flow to control the speed. Won't slice with supports on.

**Expected behavior**
I expected the slicer to work with supports.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/3137075/3239231c-991c-42d4-be6b-597cb9b3f76b)

**Printer model**
Elegoo Neptune 3 Pro on Klipper

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.6.3

**Comment by dvomang** [comment]
This is resolved when I change the default line width from 0 to 0.6
![image](https://github.com/SoftFever/OrcaSlicer/assets/3137075/18737844-d1d1-4ed4-a102-f0062965af94)

**Comment by 5teveO** [comment]
I have has the same issue - when all widths are 0. Change to 0.4 (or probably anything) and its fine

**Comment by scottmudge** [comment]
This PR fixes it.

**Comment by MxBrnr** [comment]
This is still an issue as of 2.2.0-beta2. In my case it appears to be connected to using Archne and having the inner wall line width set to anything less than 110% of nozzle diameter.

**Comment by 95zrjdtyrj** [comment]
It is relevant for version 2.3.2 if the width of the solid fill line is 0.4 or 0.41 with a nozzle diameter of 0.4. If you set 0.42, then there is no error.

**Comment by Noctyon** [comment]
At the moment I am using orca slicer 2.3.1 and klipper I haven't noticed any errors like that anymore
