### ISSUE TITLE
Only one wall at top surfaces issue

### ISSUE THREAD

**Issue by streetgt** [SoftFever/OrcaSlicer#4285]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

Not revelant

### Printer

Not revelant

### How to reproduce

With Only one wall at top is creating some kind of layer artifacts, if disabled works great.

With Only one wall at top surfaces - Enabled
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/2b2a23c6-3564-4df3-b7d6-4d8f8bc4238d)

Only one wall at top surfaces - Disabled
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/f56cad4e-b02f-4320-80c9-52cb85dc1060)

SuperSlicer
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/842af0a8-5f5a-4740-b3d4-d85ec54ec4f2)

File provided to reproduce.
[Q-59-ZL-59.zip](https://github.com/SoftFever/OrcaSlicer/files/14466858/Q-59-ZL-59.zip)

### Actual results

Top surface contains "artifacts"

### Expected results

Surface should not contain "artifacts"

### Project file & Debug log uploads

No logs needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

No

**Comment by streetgt** [comment]
Bambu Slicer:
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/8386e6ab-6a99-4828-a2be-5a96bebe70c1)

Orca Slicer:
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/98b5d042-9e29-40a8-8d2f-02e918cc43e1)

**Comment by igiannakas** [comment]
Have you tried the latest nightly? There was a fix pushed for the one wall top layer.

**Comment by streetgt** [comment]
Still not fixed. This is an annoying bug that should be fixed.

![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/ab41fab1-50c8-4a80-ad15-b98e055ae9e9)

**Comment by streetgt** [comment]
@SoftFever can we have a fix on this instead of pushing new features?

**Comment by igiannakas** [comment]
Check super slicer and Bambu slicer if they are using Arachne for slicing with one wall, where it works. I think they are not showing this bug because of use of classic slicing.

there is an issue with Arachne plus this feature on some rare occasions. In this instance the workaround is to set classic slicing for that part.

**Comment by tiagoacardoso** [comment]
No, changing between archne and classic doesn’t fix the issue.

**Comment by igiannakas** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/0e1782d8-0c24-4867-9dee-bd0f4ce3c04d)
set one wall threshold to 100%.

**Comment by SoftFever** [comment]
For models with text embossment, it's recommended to set the threshold to 0%.

It is mentioned in the tooltip
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/67cb28e6-929a-4ed4-b710-2184b8101f7f)
